#!/bin/bash

build:
	docker build -t eureka:latest .\eureka
	docker build -t service-one:latest .\service-one
	docker build -t service-two:latest .\service-two
	docker build -t api-gateway:latest .\api-gateway