#!/bin/bash

# Build Docker images for all microservices
docker build -t eureka:1.0 ./eureka
docker build -t service-one:1.0 ./service-one
docker build -t service-two:1.0 ./service-two
docker build -t api-gateway:1.0 ./api-gateway